---
branches:
  only:
    - master

env:
  global:
    # DOCKER_EMAIL
    - secure: "D2EjsmKJ6N7qJ3ih1Y/Si8Ru3aiSjeCWTfPB29ctMLEeNTHQv3N9HKvBy2r7Ex6eLBUd9LvAZ/m2ciOzpTov3uCopjr4R2us2ENZq3jIT8AntyC7RfHIo4fEqbGgmvVqHkXxn1zpWMuUIYfJYHWY9Z11AAG9/Z09r+LbbxzeGF0C3fhu3N6ZrVkf/E+rYDy7PvvLUJMepV6Hhd2N7A5ix3jW4drPBqBhZAuYlFJCeYprwz9ZuNepv0LdpmQNdXRCTBvdeW8YIJ6x4vOkYSUQij6pk6HtQ5gkKDTRvn7amtL01pB1SA7oiEy69rXhmFAc7v01Sb0tqkJels7d6jJmiLu2Q3gpoiRVk32H7cT+jpfxiYyyXJzoiWf2x4CJrScL9NXCSHWakyk79lL9lE7gN/jP/sht5QJSY8c/1UPjy9IQvIrjA43P3tWWe/oG8vSF3KXUAMwbXwvKsoMWsLdw/+GFbO3pQEO/bId7y3RLSGcaab29KrFNSy4uaSEHZdGWZENG8H5tuvQVr5SgueHfZQSmQ/TGQZs67LG9JnnuWzdFBXBmCHQDbG8RWP/pvaIKPZCKA5UzO48z5d3HLQfp3Avs7LTOVgwSzv84/ycDPGvhIbCG6vY8VMUxkJLjCjR5vil+v4dMhIZuZx6tpgVnOB5JPjnjrK+Si6f3hd42Fqs="
    # DOCKER_USER
    - secure: "Ad5y+sNmy37k1qdFXnRltS+pFphBiCa0aLwvwuMx3Ojh0b+o+QzMPc+8RlG4w48z7Yp9Pm2Gng8Ar9ZckEslnZxlpVage7Un4JiJ1r09cVqmBDhl3fHDz//yNdV9s2i3pmFZ3D4rsWeFvW3+URpGtsutYxQhdpV+ArS5r4Y1goXjQgJOAaXEtjEanPp+YMf0PbYIeErqEMBvsc42N5xkwfXOTQc11IdovONTRvVtd9n5rpHFddM2abGQ0sWnJqCHFxSPP/V7rzkBp0Ee3TvJDsrPzJVzlklDY09T7AnD1W9JkKb8eaZPRZU2t3ABCGJwcWw/G3cnjKlszyACHofxJcjSqwLSlCFqDrPWXwdsDTW8SyeOMoMA6VVqbPnv5Zys/EEiaNbTyxPflyr/Z8w9PY95Q47JwVDaK9/ENYgA8jXuq06RPWVELNZlCsVpIgXK3y3N4ptoU2LxVAnp098Iz6hyb7u9IjVMmH6ieU/xGLTBjBW0Dv4vygheFKOw1AIlQuxjph8I95ibrSjImMkZRZzhvpVsBCEf89gaWxIxSAakaVFt22skYuVEd+7D6DFuu57hy+5Sh2zCJf9hTBfwQi8OKzDX/JiUOTn7jLSUv2r4emRYRYPTeb9ILb2SxZKVLC1exgxJd0ZeSgNJnhNV5a3yb5g7H03lnf5HKvau7CU="
    # DOCKER_PASS
    - secure: "E7prWemWNqSL14cXLNakwct3hs6GCz/Z2MOHFuNhIXW8MbLzBNxwQ3UYmeLeuvjC7XnowaUhppmuD90gDxre4jLAfJSSGJtJ3aUNTYu0PMCgbdeL9Crb8UbXPIXdGiroYU6IIYNTWX326g0VFeddtUBNYJjbX2p6WE9lHaPqHpi5Y1BE6fUrjdpGwifnY2UO6NwQW9DSx2p5X0n7EIJheKxbsKFsZbzONC607weWR3R+v1AtAwN4f55CZP2cuO7fh/sdKMoaAWe1QNIo0ucMU8WpZ4QtmVH9rIesDwTAQxWwp/3nz/q41/b5mxOd4NgATG8MT7WGWk+oVHF+x/tmxhauXXyJZh4AdJj/H7Pm/10i13bWM7UtF40elmKynG6J+NoDbkvYmmcXI4CwtEFQ0ORRAmX9/Ja01lsD0SDSj7zv3OWXHVr9J5ArwIf8M9+Jhu17Ie13sXzQfzrd+Jk8O/mDF6LmJjB5Ro9CLUvL0pt0wFdkR1293gkQBIVw/69EMC7xjaNTSmZy6Dp947FiBH1IwM1huJc488mdvhSUZeLlF0TgLSy2wt03G4YBfuDEM6J9xSs8bfQR3zNcWAdlHUMcGsA5hHC5LAutizCB6Bzu3JYCK1ltlcyQGfIg50fgdue+2oLrIiUvgYpVBXJL6lMSjymyzZdWHVsS61Rk9eg="
    - DOCKER_REPO=spreadspace/ffmpeg-streaming

script:
  ### pull current images to potentially use docker build cache
  - docker pull $DOCKER_REPO:latest
  ### build the new images
  - docker build -t $DOCKER_REPO:latest .
  - docker tag $DOCKER_REPO:latest $DOCKER_REPO:$TRAVIS_BUILD_NUMBER
  ### push to docker-hub
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $DOCKER_REPO:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_REPO:latest
